version: '3.7'
services:

  app:
    build: .
    image: app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8080"]
    # command: ["tail", "-f", "/dev/null"]
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    # depends_on:
    #   - broker

  # worker:
  #   build: .
  #   image: *app
  #   restart: "no"
  #   env_file: *envfile
  #   command: ["celery", "worker", "--app=worker.worker.app", "--concurrency=1", "--hostname=worker@%h", "--loglevel=INFO"]
  #   volumes:
  #     - ./app:/app
  #   depends_on:
  #     - broker
    
  # flower:
  #   image: zoomeranalytics/flower:0.9.1-4.0.2
  #   restart: "no"
  #   env_file: *envfile
  #   ports:
  #     - "5555:5555"
  #   depends_on:
  #     - broker

  # broker:
  #   image: rabbitmq:3-management
  #   env_file:
  #     - .env
  #   ports:
  #     - 5672:5672
  #     - 15672:15672