version: '3.7'
services:

  app:
    build: .
    image: app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8080"]
    # command: ["tail", "-f", "/dev/null"]
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - broker

  worker:
    build: .
    image: worker
    env_file:
      - .env
    command: ["celery", "worker", "--app=carsite", "--beat", "--concurrency=1", "--hostname=worker@%h", "--loglevel=INFO"]
    # command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./app:/app
    depends_on:
      - broker
    
  # flower:
  #   image: mher/flower
  #   env_file:
  #     - .env
  #   # command: ["tail", "-f", "/dev/null"]
  #   command: ["flower", "--broker=$CELERY_BROKER", "--port=5555"]
  #   ports:
  #     - "5555:5555"
  #   depends_on:
  #     - broker

  broker:
    image: rabbitmq:3-management
    env_file:
      - .env
    ports:
      - 5672:5672
      - 15672:15672