# Generated by Django 2.2.7 on 2019-11-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumberPlate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=6)),
                ('owner', models.CharField(max_length=255)),
                ('car_model', models.CharField(max_length=255)),
            ],
        ),
    ]
