# Generated by Django 2.2.7 on 2019-11-13 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, max_length=255, verbose_name='Car Manufacturer')),
                ('model', models.CharField(blank=True, max_length=255, verbose_name='Car Model')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('ctask_status', models.CharField(choices=[('IN PROGRESS', 'In progress'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='IN PROGRESS', max_length=255, verbose_name='Celery task state')),
                ('ctask_message', models.CharField(blank=True, max_length=255, verbose_name='Celery message')),
            ],
        ),
        migrations.AlterField(
            model_name='numberplate',
            name='car_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='number_plates', to='api.CarModel'),
        ),
        migrations.AlterField(
            model_name='numberplate',
            name='number',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
