# Generated by Django 2.2.7 on 2019-11-09 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191109_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='manufacturer',
            field=models.CharField(default='', max_length=255, verbose_name='Car Manufacturer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='model',
            field=models.CharField(default='', max_length=255, verbose_name='Car Model'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='numberplate',
            name='car_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='number_plates', to='api.CarModel'),
        ),
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together={('manufacturer', 'model')},
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='name',
        ),
    ]
