# Generated by Django 2.2.7 on 2019-11-18 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191113_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberplate',
            name='number',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_number_plate', message='Plate number should contain first three alphabetical letters follewed by three numbers. exmp.: ABC123', regex='[A-Za-z]{3}\\d{3}')]),
        ),
        migrations.AlterField(
            model_name='numberplate',
            name='owner',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_owner', message='Please use alphanumeric symbols', regex='[A-Za-z]')]),
        ),
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together={('manufacturer', 'model')},
        ),
    ]
