# Generated by Django 2.2.7 on 2019-11-18 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191118_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberplate',
            name='owner',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_owner', message='Please use alphanumeric symbols', regex='^[A-Za-z ]+$')]),
        ),
    ]
