# Generated by Django 2.2.7 on 2019-11-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191109_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, verbose_name='Car Manufacturer'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='model',
            field=models.CharField(blank=True, max_length=255, verbose_name='Car Model'),
        ),
    ]
